New Designed Logo For StyleShare
VaibhavArora314/StyleShare pull request #121
Opened 2024-06-05 08:42 UTC by MehtabAsHellic

# Pull Request

### Title
New Designed Logo For StyleShare

### Description
Designed Logo For StyleShare is added in the frontend folder of the project.

### Related Issues

### Changes Made

### Checklist 

- [ ] I have tested the changes locally
- [ ] Documentation has been updated (if necessary)
- [ ] Changes are backward-compatible

### Screenshots (if applicable)
![SS1](https://github.com/VaibhavArora314/StyleShare/assets/101495398/69a07638-5c67-4bc7-9bf3-76497d63f092)
![ss2](https://github.com/VaibhavArora314/StyleShare/assets/101495398/cfd19c16-9d8f-4b9f-8b92-c9ba23479d3b)

### Additional Notes

Footer

2024-06-05 17:53 UTC, VaibhavArora314 requested changes
Keep the files in frontend/src/assets/logo/

2024-06-06 04:04 UTC, MehtabAsHellic commented
> Keep the files in frontend/src/assets/logo/

ok

2024-06-06 04:06 UTC, MehtabAsHellic commented
> > Keep the files in frontend/src/assets/logo/
> 
> ok

Please check @VaibhavArora314 now

2024-06-06 05:02 UTC, VaibhavArora314 approved these changes

2024-06-06 05:02 UTC, merged