Fixed the bug of pages rendering at bottom
VaibhavArora314/StyleShare pull request #151
Opened 2024-06-08 14:47 UTC by pani2004

Fixed the bug of pages rendering at bottom

Solved issue #141 
- [ x] I have tested the changes locally
- [ x] Changes are backward-compatible

https://github.com/VaibhavArora314/StyleShare/assets/154724111/7733d40d-2cf7-48d3-947d-50c3f23995cb

2024-06-08 14:49 UTC, pani2004 commented
@VaibhavArora314 Pls review the PR!!!!

2024-06-09 04:16 UTC, VaibhavArora314 requested changes
good work, just rename that component as ScrollToTopWhenRouteChanges because we also have a scroll to top button and it can be confused with it currently

2024-06-09 07:05 UTC, pani2004 commented
@VaibhavArora314 Made the changes

2024-06-09 08:11 UTC, VaibhavArora314 approved these changes

2024-06-09 08:11 UTC, merged