Google Auth
VaibhavArora314/StyleShare pull request #284
Opened 2024-06-23 13:57 UTC by naisargi17

### Description
Google authentication 

### Related Issues

### Changes Made
firebase is use for google authentication 

### Checklist 

- [ X] I have tested the changes locally
- [ X] Documentation has been updated (if necessary)
- [ X] Changes are backward-compatible

### Screenshots (if applicable)

### Additional Notes

Footer

2024-06-23 14:02 UTC, VaibhavArora314 commented
resolve merge conflicts and following errors
![image](https://github.com/VaibhavArora314/StyleShare/assets/84830429/a281c693-0872-4548-a20d-08b3a8f88e97)

2024-06-23 16:40 UTC, naisargi17 commented
yes , I 'm working on but I facing issues here also.
![image](https://github.com/VaibhavArora314/StyleShare/assets/111778403/7c61b116-d8d7-424a-a47b-d32ea8fb18c4)

2024-06-30 11:12 UTC, naisargi17 commented
Hi @VaibhavArora314  can assist me where is this confilct coming from ?

2024-06-30 14:34 UTC, VaibhavArora314 commented
> Hi @VaibhavArora314 can assist me where is this confilct coming from ?

there is an error in usePosts hook. also resolve merge conflicts.
![image](https://github.com/VaibhavArora314/StyleShare/assets/84830429/fb6d2ad9-16a0-40d8-91ae-ce4d32a6ff64)

2024-07-01 07:57 UTC, VaibhavArora314 requested changes
dont pass your firebase credentials, pass them as env variables
remove package-lock.json from root of the project
resolve merge conflicts

2024-07-02 04:44 UTC, VaibhavArora314 requested changes
also, resolve merge conflicts

2024-07-02 04:44 UTC, VaibhavArora314 commented on frontend/src/firebase.tsx
the secrets here should not be directly written in code, put them as environment variables

2024-07-02 06:24 UTC, Ultimateutkarsh11 approved these changes
Kindly resolve the merge conflicts, rest is fine.

2024-07-02 07:01 UTC, naisargi17 commented on frontend/src/firebase.tsx
Yes I'm working on it ...there is some updates in firebase so I'm working on it .

2024-07-02 07:02 UTC, naisargi17 commented
> Kindly resolve the merge conflicts, rest is fine.

I'm resolving it .please give me some time .

2024-07-03 12:24 UTC, closed without merging