[Feature Request]: Email on Contact Us
VaibhavArora314/StyleShare pull request #360
Opened 2024-07-03 14:45 UTC by sivaprasath2004

# Pull Request

### Title
[Feature Request]: Email on Contact Us

### Description
The mail will be Announced.

### Related Issues
Fixes #334 

### Changes Made
- Improvements

### Checklist 

- [ ] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [ ] Changes are backward-compatible

### Screenshots (if applicable) 

[Screencast from 2024-07-03 20-05-18.webm](https://github.com/VaibhavArora314/StyleShare/assets/121082414/eb4c91fa-d94c-437f-b887-d292d4615d5f)

![WhatsApp Image 2024-07-03 at 8 06 59 PM](https://github.com/VaibhavArora314/StyleShare/assets/121082414/d44336e5-77cb-454a-919a-eb83a5950d56)

### Additional Notes

Footer

2024-07-03 14:47 UTC, sivaprasath2004 commented
@VaibhavArora314 i will finished it ...
please merge..

2024-07-03 16:29 UTC, VaibhavArora314 requested changes
as I stated in the issue, also add content of the contact us form filled by the user in the email

2024-07-03 17:30 UTC, akbatra567 commented on backend/src/helpers/mail/ContactUsMail.ts
> +export const mailing=async (email: string, username: string) =>{
Username is unused. could you mention what was the intention behind it ?

2024-07-03 17:33 UTC, akbatra567 commented on backend/src/helpers/mail/ContactUsMail.ts
> +    from:'no_reply<yourapp@example.com>',
```suggestion
    from: process.env.FROM_EMAIL,
```

make this configurable from the environment variables.

2024-07-04 01:42 UTC, sivaprasath2004 commented
Hello @VaibhavArora314 , @akbatra567 

- I will finish it...

![WhatsApp Image 2024-07-04 at 7 07 27 AM](https://github.com/VaibhavArora314/StyleShare/assets/121082414/dfc3fbd4-0d69-4061-8a70-3ed64ddd0ff6)

2024-07-04 13:14 UTC, VaibhavArora314 reviewed
increase the font size of message, rest looks good
![image](https://github.com/VaibhavArora314/StyleShare/assets/84830429/d997255b-ea48-4ecc-960f-ced61a7b0562)

2024-07-05 01:28 UTC, sivaprasath2004 commented
@VaibhavArora314  which one increase `Your Message`

2024-07-05 01:37 UTC, sivaprasath2004 commented
Hello @VaibhavArora314 

![Screenshot from 2024-07-05 07-07-26](https://github.com/VaibhavArora314/StyleShare/assets/121082414/410787c2-248f-4ea0-a5ae-6bf4019746d4)

changed it...

2024-07-05 01:55 UTC, VaibhavArora314 approved these changes

2024-07-05 08:01 UTC, Ultimateutkarsh11 approved these changes

2024-07-05 09:45 UTC, merged