Feat: Added Preloader in edit post successfully Issue 363
VaibhavArora314/StyleShare pull request #368
Opened 2024-07-04 04:53 UTC by MeetDOD

# Pull Request Resolves [#363 ]

### Title: Added Preloader in edit post successfully.

### Description

1. Added the preloader as Loader (from components) in the edit post page.

### Related Issues
Fixes #363 

### Changes Made
New features: Added Preloader in edit post.

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

2024-07-04 13:21 UTC, VaibhavArora314 reviewed
looks good to me, just don't push changes of your other pull request

2024-07-04 13:44 UTC, MeetDOD commented
@VaibhavArora314 I was trying to avoid it at all the cost but it happens sometime by mistakenly :(

2024-07-04 16:46 UTC, MeetDOD commented
@akbatra567 @Ultimateutkarsh11 Please review this pr, if any issue let me know 😄

2024-07-05 07:54 UTC, Ultimateutkarsh11 approved these changes

2024-07-05 14:10 UTC, MeetDOD commented
Done

2024-07-06 04:26 UTC, MeetDOD commented
@akbatra567 please review this PR 🙏

2024-07-06 04:46 UTC, akbatra567 requested changes

2024-07-06 04:46 UTC, akbatra567 commented on frontend/src/pages/Signin.tsx
> +  document.title='Style Share | Login page 👋'
remove this duplicated line.

2024-07-06 04:56 UTC, MeetDOD commented on frontend/src/pages/Signin.tsx
> +  document.title='Style Share | Login page 👋'
Done @akbatra567

2024-07-06 06:50 UTC, VaibhavArora314 requested changes
captcha is twice on sign in page

2024-07-06 07:34 UTC, MeetDOD commented on frontend/src/pages/Signin.tsx
![image](https://github.com/VaibhavArora314/StyleShare/assets/120380073/1cdef99f-f830-4743-aabd-91000366d796)

@VaibhavArora314  Where it is ? Everything is fine !

2024-07-06 07:36 UTC, VaibhavArora314 commented on frontend/src/pages/Signin.tsx
![image](https://github.com/VaibhavArora314/StyleShare/assets/84830429/cd7d8cfe-53a5-41f2-97d4-8dfa4a0d547d)

2024-07-06 07:39 UTC, akbatra567 requested changes

2024-07-06 07:39 UTC, akbatra567 commented on frontend/src/pages/Signin.tsx
>            <div className="flex justify-center">
remove this duplicate code.

2024-07-06 07:40 UTC, MeetDOD commented on frontend/src/pages/Signin.tsx
@VaibhavArora314 Done the changes check now !

2024-07-06 07:41 UTC, VaibhavArora314 approved these changes

2024-07-06 07:42 UTC, MeetDOD commented on frontend/src/pages/Signin.tsx
>            <div className="flex justify-center">
@akbatra567  already did this

2024-07-06 18:33 UTC, MeetDOD commented
@akbatra567 review this pr because i want to work on other issues also, if you are available 👍

2024-07-06 18:35 UTC, akbatra567 approved these changes

2024-07-06 18:35 UTC, merged