Update Footer.tsx
VaibhavArora314/StyleShare pull request #371
Opened 2024-07-05 06:52 UTC by Prabhatyadav60

# Pull Request

### Title
Add Favicons to Footer Section

### Description
This pull request adds favicons to the footer section of the website, improving its visual appeal and user experience.

### Related Issues

Fixes #370 

### Changes Made
Added favicons to the footer section, including icons for "About Us," "Contact Us," and "Admin Dashboard."
Moved the favicons to the left side of their respective text for consistency and improved design.

### Checklist 

- [x] I have tested the changes locally
- [ ] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)
![favicons](https://github.com/VaibhavArora314/StyleShare/assets/133522303/22a542ac-926e-462e-a1ba-298ba083d59d)

### Additional Notes

@VaibhavArora314  kindly review this pull request. Thank you.
Footer

2024-07-05 07:53 UTC, VaibhavArora314 approved these changes

2024-07-05 08:13 UTC, Ultimateutkarsh11 requested changes
Hey @Prabhatyadav60 good work, can you add icons for the 'Legal Pages' Section also?

2024-07-05 09:42 UTC, Prabhatyadav60 commented
@Ultimateutkarsh11  added icons for the 'Legal Pages' Section

2024-07-06 04:40 UTC, Ultimateutkarsh11 approved these changes

2024-07-07 09:37 UTC, VaibhavArora314 commented
@akbatra567 kindly review this

2024-07-08 05:00 UTC, merged