Feat/editable profile
VaibhavArora314/StyleShare pull request #376
Opened 2024-07-05 20:58 UTC by anwesha2002

# Pull Request

### Title
Feature update :  Editable profile #127

### Description
this PR adds the feature of the editable profile. User can edit their profile in profile section

### Related Issues
Fixes #127 

### Changes Made
- An edit form added for user profile update.
- profile_update route and controller is added in the backend
- All the necessary changes made in the frontend and the backend for this feature
- Zod verification is also taken care of

### Checklist 

- [x ] I have tested the changes locally
- [x ] Documentation has been updated (if necessary)
- [x ] Changes are backward-compatible

### Screenshots (if applicable)
https://github.com/VaibhavArora314/StyleShare/assets/116761608/8982eb69-0655-4e2e-84bf-a87278fbb958

### Additional Notes
HMU if any changes needed

Footer

2024-07-06 07:00 UTC, VaibhavArora314 requested changes
![image](https://github.com/VaibhavArora314/StyleShare/assets/84830429/4fae2588-0400-4c18-bf3d-f3fd28f99fbf)
resolve these errors

2024-07-06 07:08 UTC, VaibhavArora314 requested changes
looks good to me, some things to change:
1. don't use contains in updating as it is affecting all users
2. check if email already in use by other user
3. if user changes email, mark user verified status to false

2024-07-06 07:20 UTC, anwesha2002 commented
@VaibhavArora314 I think there is no function named 'updateFirst'. in order to do so first will have to do findFirst and then 'update' that record. otherwise if i use updateMany, all the data contains that userID will be updated means in follow list, or in post or where ever it is in use.
so should I change it??

2024-07-06 07:24 UTC, VaibhavArora314 commented
> @VaibhavArora314 I think there is no function named 'updateFirst'. in order to do so first will have to do findFirst and then 'update' that record. otherwise if i use updateMany, all the data contains that userID will be updated means in follow list, or in post or where ever it is in use. so should I change it??

there is a method named update

2024-07-06 07:28 UTC, VaibhavArora314 commented
or you can dont use contains while updating since that is affecting multiple user I guess

2024-07-06 08:22 UTC, anwesha2002 commented
> don't use contains while updating since that is affecting multiple users. you can use updateMany but don't use contains for id in where

okay

2024-07-06 19:09 UTC, akbatra567 commented on frontend/src/components/profileForm.tsx
> +            const axiosError = e as AxiosError<{
Avoid `as` whenever possible as it does a force conversion to the specified type. 

Potential solution is: 
```suggestion
            const axiosError: AxiosError<{ error: { message: string; }}> = e;
```
You would need to test if it directly works also if you fell the error is commonly used, you can create a type and pass directly. 

For instance: 
```ts
type ErrorType = { error: { message: string; }};
const axiosError: AxiosError<ErrorType> = e;
```

2024-07-06 19:13 UTC, akbatra567 commented on frontend/src/components/profileForm.tsx
> +                    return axiosError?.response?.data?.error as typeof e;
See here also if you can avoid type convertion using `as` keyword. If it doesn't work you can avoid. Do try and let me know.

2024-07-07 06:29 UTC, Ultimateutkarsh11 requested changes
@anwesha2002 LGTM

2024-07-11 11:03 UTC, VaibhavArora314 requested changes
looking but after the user updates his details, the updated details should be shown on the profile as currently, it is showing old details

2024-07-11 15:01 UTC, anwesha2002 commented
> looking good but after the user updates his details, the updated details should be shown on the profile as currently, it is showing old details and user has to reload to see updated details

is it okay now??

2024-07-11 18:01 UTC, VaibhavArora314 approved these changes

2024-07-12 11:19 UTC, Ultimateutkarsh11 approved these changes

2024-07-12 16:14 UTC, akbatra567 approved these changes

2024-07-12 16:15 UTC, merged