Feat: Fetched Trending and New Posts in admin dashboard successfully Issue 366
VaibhavArora314/StyleShare pull request #385
Opened 2024-07-06 20:19 UTC by MeetDOD

# Pull Request Resolves [#366 ]

### Title: Fetched Trending and New Posts in admin dashboard successfully.

### Description

1. I am fetching the posts of total 6 in both the table, fetching from posts with pagination and the trending posts.
2. Created interface for post and user.

### Related Issues
Fixes #366 

### Changes Made
New features: Fetched Trending and New Posts in admin dashboard.

### Screenshots

![image](https://github.com/VaibhavArora314/StyleShare/assets/120380073/22cf9108-13ef-4f54-a06c-6a39fab38ec9)

![image](https://github.com/VaibhavArora314/StyleShare/assets/120380073/d8a899de-dc37-4e22-9835-d2370f3e77bf)

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

2024-07-07 05:16 UTC, MeetDOD commented
@VaibhavArora314 @Ultimateutkarsh11 @akbatra567 please review this 😄

2024-07-07 09:40 UTC, VaibhavArora314 requested changes
I think we should not provide fields such as email on the posts endpoint since email has to be hidden, rather you can create a separate endpoint for admin/post to get posts with email and other extra details.

2024-07-07 09:52 UTC, MeetDOD commented
> I think we should not provide fields such as email on the posts endpoint since email has to be hidden, rather you can create a separate endpoint for admin/post to get posts with email and other extra details.

I didn't get it what are you saying, can explain me in brief please :_)

2024-07-07 09:54 UTC, MeetDOD commented
> I think we should not provide fields such as email on the posts endpoint since email has to be hidden, rather you can create a separate endpoint for admin/post to get posts with email and other extra details.

Like even if we hide the email directly or indirectly anyone can see the email ! no hiding is not the solution i think .

2024-07-07 11:14 UTC, MeetDOD commented
@VaibhavArora314 Done the changes as requested level 3 because of api and frontend 😄 !

2024-07-08 01:28 UTC, akbatra567 commented on admin/src/components/NewPosts.tsx
> +      console.log(response.data.posts);
remove this console.log statement.

2024-07-08 01:28 UTC, akbatra567 commented on admin/src/components/TrendingPosts.tsx
> +      // console.log(response.data.trendingPosts);
remove the comment.

2024-07-08 04:54 UTC, VaibhavArora314 requested changes
change route names to /admin/posts/all and /admin/posts/trending

2024-07-08 06:01 UTC, MeetDOD commented
> change route names to /admin/posts/all and /admin/posts/trending

@VaibhavArora314 Changed the routes as per request 👍

2024-07-08 06:02 UTC, MeetDOD commented on admin/src/components/NewPosts.tsx
> +      console.log(response.data.posts);
Removed

2024-07-08 06:02 UTC, MeetDOD commented on admin/src/components/TrendingPosts.tsx
> +      // console.log(response.data.trendingPosts);
Removed

2024-07-08 06:09 UTC, VaibhavArora314 approved these changes

2024-07-08 06:25 UTC, akbatra567 approved these changes

2024-07-08 08:59 UTC, Ultimateutkarsh11 reviewed
@MeetDOD kindly resolve the merge conflicts

2024-07-08 09:12 UTC, MeetDOD commented
> @MeetDOD kindly resolve the merge conflicts

Done please add level 3 label because of api + frontend 😄

2024-07-08 09:14 UTC, Ultimateutkarsh11 approved these changes

2024-07-08 09:16 UTC, merged

2024-07-08 09:17 UTC, MeetDOD commented
@Ultimateutkarsh11 can i work on issue #389 now because the block feature is done ?

2024-07-08 09:26 UTC, Ultimateutkarsh11 commented
> @Ultimateutkarsh11 can i work on issue #389 now because the block feature is done ?

Yes, go ahead.