fix margins in navbar for mobile screen
VaibhavArora314/StyleShare pull request #386
Opened 2024-07-07 11:04 UTC by zalabhavy

# Pull Request

### Title
In mobile screen navbar section sing in/sing up and mode change button not have proper margin

### Description
Added margins when mobile menu is open.

### Related Issues
Fixes #353

### Changes Made
Added style for margins

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)

![image](https://github.com/VaibhavArora314/StyleShare/assets/126322584/c0bcf2f0-a9c2-427d-bfff-93b90c883f39)

2024-07-07 11:05 UTC, zalabhavy commented
@VaibhavArora314 @Ultimateutkarsh11 @akbatra567 Please check it and merge !

**Thank You !**

2024-07-07 11:40 UTC, akbatra567 commented on frontend/src/components/Navbar.tsx
> +                    className={`inline-flex mt-1 border-2 border-white items-center justify-center w-10 h-10 text-gray-100 rounded-lg hover:bg-blue-400 focus:outline-none focus:ring-2 focus:ring-gray
could be combined in one condition than comparing 3 times ?

2024-07-07 13:06 UTC, zalabhavy commented
@akbatra567 Done !

2024-07-07 15:08 UTC, akbatra567 approved these changes

2024-07-07 18:15 UTC, zalabhavy commented
@VaibhavArora314 @Ultimateutkarsh11 please check it and merge!
Thank you 🙏

2024-07-08 04:51 UTC, VaibhavArora314 requested changes
![image](https://github.com/VaibhavArora314/StyleShare/assets/84830429/c2caf864-562d-4be4-ac65-9227ce5db693)

2024-07-08 12:42 UTC, closed without merging