Feat: Added Manging Block users in frontend successfully issue 389
VaibhavArora314/StyleShare pull request #391
Opened 2024-07-08 11:03 UTC by MeetDOD

# Pull Request Resolves [#389 ]

### Title: Added Manging Block users in frontend successfully.

### Description

1.  In Backend at user, i created a route and controller for checkingBlockOrUnblock at user side if the blocked is true that it will return the true and false similarly.
2.  In frontend, I created a Blocked page which show some text and email of the admin.
3.  In App.tsx i am checking the true/false with the help of useBlock hook which i created in the hooks folder which is fetching the status from backend.
4.  The Design is responsive.

### Related Issues
Fixes #389

### Changes Made
New features: Added Manging Block users in frontend.

### Screenshots

![image](https://github.com/VaibhavArora314/StyleShare/assets/120380073/0b501237-65cc-4cff-af68-c05fd3ca715c)

### Video

https://github.com/VaibhavArora314/StyleShare/assets/120380073/fe3b3bc0-f0e3-4c5d-811a-dcf851c6bf61

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

2024-07-08 11:04 UTC, MeetDOD commented
@VaibhavArora314 I created a types.ts where all the interface is situated and I am using IPost and IUser in other files as I promised !

2024-07-08 13:23 UTC, VaibhavArora314 requested changes
rest is looking good to me, just this one change

2024-07-08 13:23 UTC, VaibhavArora314 commented on frontend/src/hooks/userBlock.tsx
here we can use setInterval to check user block status every 5 or 10 minutes and we can store interval value in a state to  remove or update interval

2024-07-08 13:27 UTC, MeetDOD commented on frontend/src/hooks/userBlock.tsx
Interval means, can you tell me more about it ! I haven't use interval approach in my projects can you elaborate please 😄

2024-07-08 17:49 UTC, MeetDOD commented
> rest is looking good to me, just this one change and also add an logout button on account suspend page

@VaibhavArora314 logout button done 👍

2024-07-09 05:26 UTC, VaibhavArora314 commented on frontend/src/hooks/userBlock.tsx
I got this sample code snippet of a hook to fetch todos and refresh them after a while, you can take reference from this

```
import { useEffect, useState } from 'react';
import axios from 'axios';

// Custom hook for fetching todos with auto-refresh
function useTodos(n) {
  const [loading, setLoading] = useState(true);
  const [todos, setTodos] = useState([]);

  // Function to fetch data from the backend
  function getData() {
    axios.get("<api-url-here>")
      .then(res => {
        setTodos(res.data.todos);
        setLoading(false);
      })
      .catch(error => {
        console.error("Error fetching todos:", error);
        setLoading(false);
      });
  }

  useEffect(() => {
    // Initial data fetch
    getData();

    // Set up interval to fetch data every n seconds
    const intervalId = setInterval(() => {
      getData();
    }, n * 1000);

    // Clean up the interval on component unmount or when n changes
    return () => clearInterval(intervalId);
  }, [n]);

  // Return todos and loading state
  return {
    todos: todos,
    loading: loading
  };
}

// Main App component
function App() {
  // Using the custom hook to fetch todos with auto-refresh every 5 seconds
  const { todos, loading } = useTodos(5);

  // Rendering loading message if data is still loading
  if (loading) {
    return <div>Loading...</div>;
  }

  // Rendering Track component for each todo
  return (
    <>
      {todos.map(todo => <Track key={todo.id} todo={todo} />)}
    </>
  );
}
```

2024-07-09 07:38 UTC, MeetDOD commented on frontend/src/hooks/userBlock.tsx
So, basically you want that api doesn't hit after every reload like that ?
because of this you want to implement this feature right @VaibhavArora314 ?

2024-07-09 08:20 UTC, MeetDOD commented on frontend/src/hooks/userBlock.tsx
@VaibhavArora314 Amazing bro thank you very much i learned very new feature today,
I implemented it so, basically i add the timeout and updating state according to the time i set it to every 5 minute, so if admin unblock/block the user without reloading the page will update to suspended page.
So, if user is in the app and he/she is scrolling and using the app but when admin block the user, after 5 min the get api is called and user will dynamically see the suspended page.

Thank You very much 😄🙏

2024-07-09 14:00 UTC, VaibhavArora314 approved these changes

2024-07-09 17:24 UTC, Ultimateutkarsh11 approved these changes

2024-07-10 09:15 UTC, akbatra567 approved these changes

2024-07-10 09:15 UTC, merged

2024-07-10 09:22 UTC, MeetDOD commented
Added GSSOC label and level

2024-07-10 09:23 UTC, MeetDOD commented
Add GSSOC label and level !

2024-07-10 09:41 UTC, MeetDOD commented
@VaibhavArora314 @Ultimateutkarsh11 please add label and level gssoc