Enhanced "The Cursor Trail Effect" To Increase UI
VaibhavArora314/StyleShare pull request #408
Opened 2024-07-10 08:09 UTC by MastanSayyad

### Title

- Issue fixes #405 

### Description

Hey @VaibhavArora314 

I have enhanced and re-created the cursor trail effect to the website 

### Changes Made

**The effect consists of:**
- Multiple circles that follow the cursor, creating a visually appealing trail as the user moves the mouse. 
- The `circles` have a gradient background and gradually scale down, giving a dynamic and interactive user experience.
- Color gradient `#cefbff` `#0325ff`
- The `.circle-container` class ensures that the circles are positioned fixed and cover the entire viewport, with pointer-events disabled to allow user interaction with underlying elements

### Screenshots

https://github.com/VaibhavArora314/StyleShare/assets/101971980/38e0173a-c6a2-48c5-b3c8-7ec306bcd40b

### Checklist 

- [x] I have tested the changes locally
- [x] Changes are backward-compatible

2024-07-11 10:56 UTC, VaibhavArora314 requested changes
instead of adding so div with the class circle manually, is it possible to add these with a loop in js like before

2024-07-11 11:41 UTC, MastanSayyad commented
> instead of adding so many div with the class circle manually, is it possible to add these with a loop in js like before

Yes it is possible, I'll make the changes right away!

2024-07-11 20:37 UTC, MastanSayyad commented
@VaibhavArora314, @akbatra567 and @Ultimateutkarsh11 Please take a look and review it, thank you!

2024-07-12 09:10 UTC, VaibhavArora314 approved these changes

2024-07-12 11:22 UTC, Ultimateutkarsh11 approved these changes

2024-07-12 16:18 UTC, akbatra567 approved these changes

2024-07-12 16:18 UTC, merged