Fix image to stop wasting of space
VaibhavArora314/StyleShare pull request #417
Opened 2024-07-11 12:31 UTC by zalabhavy

# Pull Request

### Title
In Privacy Policy, Terms and Conditions, Cookie Policy image takes lots of space in left side. 

### Description

Fix image like 

Privacy Policy (image as a symbol)

Added hover scale on that image for user feel.

By this save space wasting in left side and get better view in small screen.

### Related Issues

Fixes #383 

### Changes Made

Change position of image and style.

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)
![WhatsApp Image 2024-07-11 at 17 54 47_b4199fbe](https://github.com/VaibhavArora314/StyleShare/assets/126322584/373a78dd-0d2d-45b8-a06e-04ffc48d81f6)

![WhatsApp Image 2024-07-11 at 17 55 00_82387d55](https://github.com/VaibhavArora314/StyleShare/assets/126322584/619d30b1-8a09-493e-b0a1-8421633e7bcf)

![WhatsApp Image 2024-07-11 at 17 55 11_c023a685](https://github.com/VaibhavArora314/StyleShare/assets/126322584/bf7fcd33-ad3d-4ed8-8819-79383ce55f53)

**In small size screen looks great now**

![WhatsApp Image 2024-07-11 at 17 55 34_06b3b439](https://github.com/VaibhavArora314/StyleShare/assets/126322584/bf9ee465-c385-44bb-b6ba-7f94fed04f97)

2024-07-11 12:32 UTC, zalabhavy commented
@VaibhavArora314 @akbatra567 @Ultimateutkarsh11 Please check it and merge !

**Thank You !**

2024-07-12 09:17 UTC, VaibhavArora314 requested changes
looking good can you also add some margin on left and right side for larger devices as it is not looking
![image](https://github.com/user-attachments/assets/cea80d89-1eb8-4308-b47d-5e74f4327861)

2024-07-12 10:41 UTC, zalabhavy commented
@VaibhavArora314 Changes Done !

![image](https://github.com/user-attachments/assets/7ad59223-97bf-4fa6-af0e-096ceda0aa08)

2024-07-12 10:54 UTC, VaibhavArora314 approved these changes

2024-07-12 12:08 UTC, Ultimateutkarsh11 approved these changes

2024-07-12 12:23 UTC, zalabhavy commented
@akbatra567 Kindly check my PR and Merge !

Thank You !

2024-07-12 16:13 UTC, akbatra567 approved these changes

2024-07-12 16:13 UTC, merged