Updated contact-us Page
VaibhavArora314/StyleShare pull request #427
Opened 2024-07-12 11:43 UTC by Prabhatyadav60

# Pull Request 

### Title
Updating Contact us page

### Description
Enhanced the contact-us page with image size adjustments with transition effect

### Related Issues
Fixes #424 
### Changes Made

Added img beside form to look good.
Added smooth transition effects for image changes.

### Checklist 

- [x] I have tested the changes locally
- [ ] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)

https://github.com/user-attachments/assets/cdbd18a9-fec8-4388-8a45-a567348af62c

### Additional Notes

Footer

2024-07-12 12:11 UTC, VaibhavArora314 requested changes
looking good but there is too much blank space on top, can you reduce it a little

![image](https://github.com/user-attachments/assets/4b20d59c-03de-4f1a-ae74-781da45bd0db)

2024-07-12 16:15 UTC, Ultimateutkarsh11 approved these changes

2024-07-13 05:55 UTC, VaibhavArora314 approved these changes

2024-07-13 10:17 UTC, akbatra567 approved these changes

2024-07-13 10:18 UTC, merged

2024-07-13 12:55 UTC, Prabhatyadav60 commented
Sir kindly add gssoc level also, Thank You !