Added preloader.
VaibhavArora314/StyleShare pull request #436
Opened 2024-07-14 08:36 UTC by happyrao78

#412 Solved.

2024-07-14 14:23 UTC, akbatra567 commented on frontend/src/main.tsx
> +// import PreLoader from './components/Loader/Loader';
remove commented code

2024-07-14 14:28 UTC, akbatra567 commented on frontend/src/App.tsx
> +  const [Preloading,setLoading]= useState(true);
```suggestion
  const [preLoading,setPreLoading]= useState(true);
```

Variable is not in react naming convention
Similar to https://react.dev/reference/react/useState#setstate

2024-07-14 15:45 UTC, VaibhavArora314 requested changes

2024-07-14 15:45 UTC, VaibhavArora314 commented on frontend/src/components/Loader/Loader.tsx
It looks great, just have one suggestion: instead of alternating between white and black colors in the preloader we can first show white then show black bg, and stop there.

2024-07-14 16:58 UTC, happyrao78 commented on frontend/src/components/Loader/Loader.tsx
As animation have also been added to the incoming text so that would  not  look good ,i tried it out. It just looks like a glitch.

2024-07-14 17:05 UTC, VaibhavArora314 commented on frontend/src/components/Loader/Loader.tsx
ok then we can go ahead with this

2024-07-14 17:06 UTC, VaibhavArora314 approved these changes
do the changes stated above rest is good

2024-07-15 08:02 UTC, Ultimateutkarsh11 approved these changes

2024-07-16 03:41 UTC, VaibhavArora314 requested changes
remove bun.lockb file and do above stated changes

2024-07-17 10:33 UTC, VaibhavArora314 commented
@happyrao78 any updates?

2024-07-26 16:37 UTC, closed without merging