added scroll to top of the bar with progrss line
VaibhavArora314/StyleShare pull request #447
Opened 2024-07-15 07:26 UTC by TheNikhilRaj

# Pull Request

Use Case
Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.
@VaibhavArora314 

Description
Feature Description
Hey, I have noticed a small issue that I believe could enhance the user experience. Currently, there is no Page Scroll Progress Bar at the Top of Your Startup Webpage , which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page. Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.

### Related Issues

### Changes Made
✨ Add a Page Scroll Progress Bar at the Top of Your Startup Webpage

### Checklist 

- [ ] I have tested the changes locally
- [ ] Documentation has been updated (if necessary)
- [ ] Changes are backward-compatible

### Screenshots (if applicable)
![343870881-7f17e9d3-41c5-4fb0-a558-caf334552764](https://github.com/user-attachments/assets/a198c131-7b5a-4c07-8abe-9b1976cc1ce0)

@VaibhavArora314

2024-07-15 10:16 UTC, VaibhavArora314 requested changes

2024-07-15 10:16 UTC, VaibhavArora314 commented on frontend/index.html
remove unnecessary comments and I cannot see the progress bar in the website

2024-07-15 13:33 UTC, akbatra567 commented on frontend/index.html
Same here can't see any progress bar, tried with both light and dark theme
![Screenshot 2024-07-15 at 7 03 22 PM](https://github.com/user-attachments/assets/9e95e97d-1737-455b-b00a-d99e6c6c371b)
![Screenshot 2024-07-15 at 7 03 34 PM](https://github.com/user-attachments/assets/2fde84e5-a847-4c79-9e8a-b07c10257cf6)

2024-07-15 19:53 UTC, Ultimateutkarsh11 requested changes
@TheNikhilRaj make the progress bar visible and resolve the merge conflicts

2024-07-15 19:57 UTC, TheNikhilRaj commented
> @TheNikhilRaj make the progress bar visible and resolve the merge conflicts

Can you please how i can setup your repo locally because it difficult to me i had tried many time but it's not go live on server "frontend" is there any solution? @Ultimateutkarsh11

2024-07-16 03:44 UTC, VaibhavArora314 commented
> > @TheNikhilRaj make the progress bar visible and resolve the merge conflicts
> 
> Can you please how i can setup your repo locally because it difficult to me i had tried many time but it's not go live on server "frontend" is there any solution? @Ultimateutkarsh11

Read this: https://github.com/VaibhavArora314/StyleShare?tab=readme-ov-file#setting-up-on-your-machine
Also don't make all the changes in index.html, create a component for it.

2024-07-19 11:52 UTC, VaibhavArora314 commented
Closing this pr since you raised other for the same

2024-07-19 11:52 UTC, closed without merging