About Us Page updated
VaibhavArora314/StyleShare pull request #448
Opened 2024-07-15 11:28 UTC by r7projects-shayan

# Pull Request

### Title
Updated the About Us page 

### Description

Updated the About Us page and made it fully responsive for all devices and dimensions
Added Interactive and sleek animations
Fixed the spacings

### Related Issues

Fixes #346 

### Changes Made

New Features and bug fixes

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)

## Video Demo

https://github.com/user-attachments/assets/a6ecd3ed-670c-49bb-a691-a2cb4c39dade

## These are the screenshots

![Screenshot 2024-07-14 202625](https://github.com/user-attachments/assets/c4ff740a-5800-499b-ad9c-7999c6e7f2e1)
![Screenshot 2024-07-14 202632](https://github.com/user-attachments/assets/3923bb36-b046-4ae2-8873-af0ebad16b8b)
![Screenshot 2024-07-14 202644](https://github.com/user-attachments/assets/e4f43009-77fa-4492-aaf2-447754212f3c)
![Screenshot 2024-07-14 202648](https://github.com/user-attachments/assets/12a12f5e-bab0-4b92-8c7d-39a0b248e2aa)
![Screenshot 2024-07-14 202703](https://github.com/user-attachments/assets/32fe81d5-6336-4dbb-939b-5fdab82ad178)
![Screenshot 2024-07-14 202710](https://github.com/user-attachments/assets/91297500-429b-474f-93d9-6a7ea638dce0)
![Screenshot 2024-07-14 202716](https://github.com/user-attachments/assets/f700cc4c-f68e-4913-8823-cf796c0b847c)
![Screenshot 2024-07-14 202744](https://github.com/user-attachments/assets/1c7235cf-8e4d-4f6d-8b2e-fe903fe70b8b)
![Screenshot 2024-07-14 202749](https://github.com/user-attachments/assets/1fdef9b0-335e-43a7-a400-7598baa4965e)
![Screenshot 2024-07-14 202755](https://github.com/user-attachments/assets/7f119c1b-d8e0-42cc-976a-6ccd4619b4e2)
![Screenshot 2024-07-14 202800](https://github.com/user-attachments/assets/4176d743-24bd-4874-bcb0-d72ba45d8d28)
![Screenshot 2024-07-14 202804](https://github.com/user-attachments/assets/ccc70b0d-0d97-417e-b46e-5775c2e00e97)

### Additional Notes

Footer

2024-07-15 11:30 UTC, r7projects-shayan commented
just give me some time I need to see the deployment error by deploying it on my personal vercel

2024-07-15 11:51 UTC, r7projects-shayan commented
Yes done now updated successfully

2024-07-15 12:47 UTC, VaibhavArora314 requested changes
It looks great, just have one suggestion that is whole website is using tailwind throughout and I don't think we should have another library for styling even though it is built top on tailwind.

2024-07-15 12:59 UTC, VaibhavArora314 commented
Also the how it works options should always be selected, we are not allowing users to select them rather we are showing what we offer and how website works

2024-07-15 16:04 UTC, r7projects-shayan commented
@VaibhavArora314 Alright I'll remove the checkbox interactivity and remove the external styling library

2024-07-15 20:09 UTC, Ultimateutkarsh11 approved these changes

2024-07-16 03:48 UTC, VaibhavArora314 reviewed
looks great, I have one question I wanted to ask what is lottieabout.json for?

2024-07-16 03:48 UTC, VaibhavArora314 commented on frontend/src/styles/about.css
remove commented code here

2024-07-16 06:08 UTC, r7projects-shayan commented
@VaibhavArora314 the lottie.json is for the animation in the about us page in place of the image

2024-07-16 06:10 UTC, r7projects-shayan commented on frontend/src/styles/about.css
done

2024-07-16 06:14 UTC, VaibhavArora314 approved these changes

2024-07-16 06:29 UTC, akbatra567 commented
@r7projects-shayan, resolve conflicts.

2024-07-16 06:29 UTC, akbatra567 approved these changes

2024-07-16 11:26 UTC, closed without merging