Google-Signup-functionality-#46
VaibhavArora314/StyleShare pull request #449
Opened 2024-07-15 12:03 UTC by mr0nerd

# Pull Request

### Title

Add Google Sign-In and Sign-Up Functionality via Firebase
### Description

This pull request introduces Google sign-in and sign-up functionality using Firebase for authentication. The frontend component handles the Google sign-in process, and the backend controller manages user creation and authentication.
### Related Issues

Fixes #46 
### Changes Made

- Added Google OAuth component to the frontend for sign-in/sign-up using Firebase
- Created a `googleAuthController` 
- Generated a random password for new Google users
- Validated user data using `signupBodySchema`
- Created tokens for authenticated users
- Sent a welcome email to newly created users
### Checklist 

- [x] I have tested the changes locally
- [ ] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)

![Screenshot 2024-07-15 171936](https://github.com/user-attachments/assets/b63d57de-a2e9-4131-8b39-05be6f2a011e)

Modified SignUp/SignIn pages

![Screenshot 2024-07-15 172033](https://github.com/user-attachments/assets/2f3b8b42-2caa-4c81-8e80-9aa600876581)

Using "Continue with Google" button to SignUp or SignIn

![Screenshot 2024-07-15 171913](https://github.com/user-attachments/assets/5dafe511-7df4-4c22-a570-dc484ec0d44a)

New user is created if its not already existing 

![Screenshot 2024-07-15 171958](https://github.com/user-attachments/assets/23f3db9f-67c7-44b6-adb0-e5cdd06293f5)

Welcome mail is sent to new user 

![Screenshot 2024-07-15 172014](https://github.com/user-attachments/assets/aa653429-c14a-434f-9fc7-9466b12fab2a)

### Additional Notes

This PR enhances the authentication system by allowing users to sign in and sign up using their Google accounts via Firebase, ensuring a smoother and faster onboarding process.
Footer

2024-07-15 12:51 UTC, VaibhavArora314 requested changes

2024-07-15 12:51 UTC, VaibhavArora314 commented on frontend/src/firebase.ts
Convert these credentials to secrets and can you also find a way to pass environment variables while serving this through backend as currently in the deployment, backend provides react app as a static resource

2024-07-15 13:40 UTC, akbatra567 commented
Hey @VaibhavArora314, 
We have another open PR for 
https://github.com/VaibhavArora314/StyleShare/pull/358

2024-07-15 15:14 UTC, mr0nerd commented on frontend/src/firebase.ts
I have converted the firebase credentials to secret.

Now to pass environment variables, i am doing following changes in the app.ts file of backend please review it 

import express, { NextFunction, Request, Response } from 'express';
import rootRouter from './routes';
import bodyParser from 'body-parser';
import cors from 'cors';
import path from 'path';
import { config } from 'dotenv';
import fs from 'fs';

config();

const app = express();
app.use(cors());
app.use(bodyParser.json());

app.get('/', (req: Request, res: Response) => {
  res.redirect('/app');
});

// Serve frontend with environment variables
app.use('/app', express.static(path.join(__dirname, '../../frontend/dist'), { maxAge: 0 }));
app.get('/app/*', (req: Request, res: Response) => {
  const indexPath = path.join(__dirname, '../../frontend/dist', 'index.html');
  let indexContent = fs.readFileSync(indexPath, 'utf-8');

  indexContent = indexContent.replace(
    '</head>',
    `<script>
      window.env = {
        VITE_FIREBASE_API_KEY: "${process.env.VITE_FIREBASE_API_KEY}",
        VITE_FIREBASE_AUTH_DOMAIN: "${process.env.VITE_FIREBASE_AUTH_DOMAIN}",
        VITE_FIREBASE_PROJECT_ID: "${process.env.VITE_FIREBASE_PROJECT_ID}",
        VITE_FIREBASE_STORAGE_BUCKET: "${process.env.VITE_FIREBASE_STORAGE_BUCKET}",
        VITE_FIREBASE_MESSAGING_SENDER_ID: "${process.env.VITE_FIREBASE_MESSAGING_SENDER_ID}",
        VITE_FIREBASE_APP_ID: "${process.env.VITE_FIREBASE_APP_ID}"
      };
    </script></head>`
  );
  res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, private');
  res.send(indexContent);
});

app.use('/admin', express.static(path.join(__dirname, '../../admin/dist'), { maxAge: 0 }));
app.get('/admin/*', (req: Request, res: Response) => {
  res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, private');
  res.sendFile(path.join(__dirname, '../../admin/dist', 'index.html'));
});

app.use('/api/v1', rootRouter);

app.use((err: Error, req: Request, res: Response, next: NextFunction) => {
  console.error(err.stack);
  res.status(500).json({ error: 'Internal Server Error' });
});

export default app;

2024-07-15 17:43 UTC, VaibhavArora314 commented
> Hey @VaibhavArora314, We have another open PR for #358 Which might be on the same lines to this.

hey @akbatra567, I asked that person if she is able to work on this issue in #46 due to repeated same problems or want someone else to work on it and she was okay with someone else working on it. Sorry, I forgot to close that pull request causing confusion.

2024-07-15 17:47 UTC, VaibhavArora314 commented on frontend/src/firebase.ts
if this works, do the changes in this pr itself so we can review it

2024-07-16 06:32 UTC, mr0nerd commented
i have made the firebase config data secret ,but please review it.

2024-07-17 10:27 UTC, VaibhavArora314 requested changes
resolve merge conflicts, and have you also added logic to pass env var to frontend?

2024-07-18 04:31 UTC, mr0nerd commented
All the requested changes have been made and merge conflicts has been resolved .so please review it.
Also, I am contributing to this repo as a GSSOC'24 contributor, so please add GSSOC  tag on this pr

2024-07-18 13:50 UTC, VaibhavArora314 requested changes
you are passing the env variables via an HTTP request currently which is a very big security loophole. is there no other way to pass the env variables securely to the frontend?

2024-07-18 13:58 UTC, VaibhavArora314 commented
On searching online, I can see that there are some ways where a token is sent from frontend to backend on google auth and it is verified on the backend then the user is signed in. Maybe you can use this method to avoid the problem of environment variables.

2024-07-26 16:36 UTC, closed without merging