Hover added on contact form image
VaibhavArora314/StyleShare pull request #453
Opened 2024-07-16 09:45 UTC by zalabhavy

# Pull Request

### Title
 Add tilt effects on contact form images.
### Description

As Per Suggestion Instead of tilt add a little horizontal movement on hover.

### Related Issues

Fixes #450 

### Changes Made

Add Tailwind Properties for better and smooth hover effects.

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)

https://www.loom.com/share/347ad239e89b47af9e22f69d4248ccf7

2024-07-16 09:46 UTC, zalabhavy commented
@VaibhavArora314 @Ultimateutkarsh11 @akbatra567 Please check it and merge !

Thank You !

2024-07-17 10:32 UTC, VaibhavArora314 requested changes
instead of translate-x do translate-y

2024-07-17 12:33 UTC, zalabhavy commented
@VaibhavArora314 Done !

2024-07-18 03:19 UTC, Ultimateutkarsh11 approved these changes

2024-07-18 13:40 UTC, VaibhavArora314 approved these changes

2024-07-18 14:10 UTC, akbatra567 approved these changes

2024-07-18 14:39 UTC, merged