Added a Page Scroll Progress Bar at the Top of Your Startup Webpage
VaibhavArora314/StyleShare pull request #465
Opened 2024-07-19 08:18 UTC by TheNikhilRaj

# Pull Request

### Title
Added a Page Scroll Progress Bar at the Top of Your Startup Webpage

### Description
Feature Description
Explain feature request
Hey @jfmartinz ,
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no Page Scroll Progress Bar at the Top of Your Startup Webpage , which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.

### Related Issues
Fixes #434 

### Changes Made

### Checklist 

- [ ] I have tested the changes locally
- [ ] Documentation has been updated (if necessary)
- [ ] Changes are backward-compatible

### Screenshots (if applicable)

![Capture](https://github.com/user-attachments/assets/88c9c0ca-3c97-43f8-80c6-ae65f09aa50f)

### Additional Notes

Footer

@VaibhavArora314 @Ultimateutkarsh11 @akbatra567 #447

2024-07-19 11:51 UTC, VaibhavArora314 requested changes
Looks good just dont do all the changes in index.html, create a component for this

2024-07-19 12:37 UTC, TheNikhilRaj commented
> Looks good just dont do all the changes in index.html, create a component for this

but i haven't done all changes is some extra lines were added okay and from my i have done this and i don't so much time for do this you tell this things when you assign me the task, but you want it i can create new issue for that then i can do, for now its done! @VaibhavArora314

2024-07-19 14:38 UTC, VaibhavArora314 commented
> > Looks good just dont do all the changes in index.html, create a component for this
> 
> but i haven't done all changes is some extra lines were added okay and from my i have done this and i don't so much time for do this you tell this things when you assign me the task, but you want it i can create new issue for that then i can do, for now its done! @VaibhavArora314

When working with any react project, it is obvious that you have to do most of your work by creating components and I already stated this in your previous pull request #447  for the same issue. As for the code that already exists in index.html was added by another contributor who was having some issues while implementing the same by creating a component which is not the case for you.

2024-07-19 14:44 UTC, TheNikhilRaj commented
You had said that on my previous PR not at the time of assign? @VaibhavArora314

2024-07-19 15:28 UTC, VaibhavArora314 commented
For now, do the changes as stated above and I won't be stating all of the changes in the issues itself. Also, it is common while contributing to open source that admins and mentors state changes on the pull request according to the work done, you cannot say no that I won't be doing these changes as you did not state in the issue.

2024-07-19 15:30 UTC, TheNikhilRaj commented
Yes I have right to say you haven't mention at the time of assign @VaibhavArora314

2024-07-19 16:09 UTC, Ultimateutkarsh11 commented
> Yes I have right to say you haven't mention at the time of assign @VaibhavArora314
Hey @TheNikhilRaj we appreciate the efforts you are putting in while making the pull requests. But, try to understand that after your work has been done and when you have raised the PR we will suggest changes only to improve it. Without seeing the work done by you, how is it possible to mention the specific changes? Understand that these changes can't be mentioned on the issue and are specific to the PR raised. Also, we have merged  460+ PRs till now and this is not the first time we are suggesting changes in the PR.

2024-07-20 05:41 UTC, TheNikhilRaj commented
@Ultimateutkarsh11 @VaibhavArora314 okay i have made seperarte file of that and only i have added 8 lines in "index.html" file for it neccesary for the issue try to understad it is neccessary to add in it!

2024-07-20 06:24 UTC, closed without merging