Feat: Added Google translator in admin panel successfully issue 364
VaibhavArora314/StyleShare pull request #466
Opened 2024-07-19 15:07 UTC by MeetDOD

# Pull Request Resolves [#364 ]

### Title: Added Google translator in admin panel successfully.

### Description

1. In admin, I created a GoogleTranslator file and imported it in SideBar also created .css file for it also,
2. I created a Sidebar Layout so that instead of calling side bar in each component I will call it only in App.tsx file and the whole app will use that.
3. Also the logout will not show the sidebar, only login person can see that.
4. The design is responsive.

### Related Issues
Fixes #364 

### Changes Made
New feature: Added Google translator in admin panel.

### Screenshots 

![image](https://github.com/user-attachments/assets/aac9e3c8-223d-45ca-bddb-d708b5ac8c06)

![image](https://github.com/user-attachments/assets/090746b3-940f-4584-87c3-eeda07c230c9)

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

2024-07-20 06:38 UTC, VaibhavArora314 requested changes
Looking good, but one thing i noticed is that sidebar is not opening on small devices

2024-07-20 07:02 UTC, MeetDOD commented
> Looking good, but one thing i noticed is that sidebar is not opening on small devices

Ha, I se, I will sort it out 👍

2024-07-20 07:16 UTC, MeetDOD commented
@VaibhavArora314 check now, I implemented it in the Layout itself, so it will not call navbar again and again in every component and hence the layout of the admin panel is maintained 😄

2024-07-20 09:51 UTC, VaibhavArora314 approved these changes

2024-07-20 10:33 UTC, akbatra567 approved these changes

2024-07-21 02:10 UTC, Ultimateutkarsh11 approved these changes

2024-07-21 02:10 UTC, merged