feat update:non copyable captcha added
VaibhavArora314/StyleShare pull request #512
Opened 2024-07-27 07:20 UTC by anwesha2002

# Pull Request

### Title
non copyable captcha feature

### Description
This PR adds a new feature that is a non copyable captcha with a graphical background for more security

### Related Issues
Fixes #471 

### Changes Made
- user cannot select captcha
- background is graphical
- hard to read the captcha

### Checklist 

- [x ] I have tested the changes locally
- [x ] Documentation has been updated (if necessary)
- [x ] Changes are backward-compatible

### Screenshots (if applicable)
![Screenshot 2024-07-27 125004](https://github.com/user-attachments/assets/33924e1f-cd76-4c1b-8a8c-98dcbf84ddf9)

### Additional Notes

Footer

2024-07-27 11:17 UTC, VaibhavArora314 requested changes
Looks good to me and works great. Just instead of plain css, can you implement these using tailwind to maintain consistency

2024-07-28 05:37 UTC, akbatra567 approved these changes

2024-07-28 05:57 UTC, VaibhavArora314 approved these changes

2024-07-28 06:20 UTC, Ultimateutkarsh11 approved these changes

2024-07-28 06:21 UTC, merged