Feat: Redirect to user profile on click of entire row in leaderboard successfully issue 404
VaibhavArora314/StyleShare pull request #514
Opened 2024-07-27 08:44 UTC by MeetDOD

# Pull Request Resolves [ #404 ]
 
### Title: Redirect to user profile on click of entire row in leaderboard successfully.

### Description

1. In frontend, I used useNavigate hook to redirect because if we user Link it will destroy the table css.
2. The design is responsive.

### Related Issues
Fixes #404 

### Changes Made
New feature: Redirect to user profile on click of entire row in leaderboard.

### Screenshots

![image](https://github.com/user-attachments/assets/a32be977-a1f3-4082-bc92-b952d756fa26)

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

2024-07-27 11:18 UTC, VaibhavArora314 requested changes
remove Link from username

2024-07-27 11:31 UTC, MeetDOD commented
> remove Link from username

@VaibhavArora314  Done 👍

2024-07-27 12:36 UTC, akbatra567 approved these changes

2024-07-27 16:25 UTC, VaibhavArora314 approved these changes

2024-07-28 04:11 UTC, Ultimateutkarsh11 approved these changes

2024-07-28 04:12 UTC, merged