Bug: Fixed responsiveness fixed in code preview tabs successfully issue 520
VaibhavArora314/StyleShare pull request #521
Opened 2024-07-27 17:23 UTC by MeetDOD

# Pull Request Resolves [ #520 ]

### Title: Fixed responsiveness fixed in code preview tabs successfully.

### Description

1. In frontend, I used the react icons for creating the icons and converted the javascript to JS.
2. The design is responsive.

### Related Issues
Fixes #520 

### Changes Made
Bug fixes: Fixed responsiveness fixed in code preview tabs.

### Screenshots

![image](https://github.com/user-attachments/assets/77b5a9f8-8f79-415f-94f6-49c2b31f5ca1)

![image](https://github.com/user-attachments/assets/1333b6f6-541d-4175-b78d-2477f75b7d8b)

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

2024-07-27 23:22 UTC, VaibhavArora314 requested changes
Show the text like edit, and copy for large devices and hide it on smaller devices

2024-07-28 06:15 UTC, MeetDOD commented
> Owner

Ok got It 👍

2024-07-28 07:43 UTC, MeetDOD commented
@VaibhavArora314 Done 👍

2024-07-28 08:04 UTC, VaibhavArora314 approved these changes

2024-07-28 08:14 UTC, akbatra567 approved these changes

2024-07-28 10:50 UTC, Ultimateutkarsh11 approved these changes

2024-07-28 10:50 UTC, merged