Add docker compose file to the root of the project
VaibhavArora314/StyleShare pull request #571
Opened 2024-08-06 10:23 UTC by haseebzaki-07

# Pull Request

### Title
This pr adds docker-compose.yaml at the root of the project

### Description
fixes #564 

### Checklist 

- [x ] I have tested the changes locally
- [x ] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

Footer

2024-08-06 14:05 UTC, VaibhavArora314 commented
Where are the dockerfiles? I think it will not work without dockerfiles if I am not wrong.

2024-08-06 19:17 UTC, haseebzaki-07 commented
I have created a separate issue for the Dockerfile(s) issue #690. I can write the Dockerfiles(s) there.

2024-08-07 18:14 UTC, haseebzaki-07 commented
I have added the Dockerfiles

2024-08-08 06:38 UTC, VaibhavArora314 reviewed
Looks good to me, just one change. Instead of passing the .env file to the backend container, only pass the database url of the mongodb container. As for the rest of the environment variables, I will add default values.

2024-08-08 07:11 UTC, haseebzaki-07 commented
Sure I'll do that

2024-08-08 07:28 UTC, haseebzaki-07 commented
I have updated the docker compose having only the DATABASE_URL as the env-variable

2024-08-08 07:38 UTC, akbatra567 requested changes

2024-08-08 07:38 UTC, akbatra567 commented on docker-compose.yml
> +version: '3.8'
```suggestion
```
Remove version field as in latest update docker has made it obsolete, removing the line fixes the issue, link for reference: https://forums.docker.com/t/docker-compose-yml-version-is-obsolete/141313

2024-08-08 12:56 UTC, VaibhavArora314 approved these changes

2024-08-08 16:25 UTC, akbatra567 approved these changes

2024-08-08 16:25 UTC, merged