Corrected the tag filter + Added placeholder for it + Minor UI Improvements
VaibhavArora314/StyleShare pull request #574
Opened 2024-08-07 06:02 UTC by Parth18Shah

# Pull Request for Issue #341 

### Title
Worked with tag filter and the UI of the posts card

### Description
Made the following changes:
- Corrected the tag filter: Made the search case insensitive
- Added placeholder for it: It now displays a couple of example tags based on the existing posts created by other users.
- Minor UI Improvements: Removed the background color from texts on the post card

### Related Issues
N.A.

### Changes Made
Answered above

### Checklist 
- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)
N.A.

### Additional Notes
N.A.

Footer

2024-08-07 10:56 UTC, VaibhavArora314 requested changes
![image](https://github.com/user-attachments/assets/4fa53ceb-ce3e-4d59-b549-538a34d8d6d8)
reactions are shown twice

2024-08-07 16:58 UTC, VaibhavArora314 commented
If there are too many then instead of showing all the placeholder tags, only show 2-3 tags and some dots after them.
@Parth18Shah

2024-08-07 17:02 UTC, Parth18Shah commented
Currently I am not displaying all the tags in the placeholder, almost 5 tags if we have at least 5 tags in our existing posts.

2024-08-08 16:26 UTC, akbatra567 approved these changes

2024-08-08 16:26 UTC, merged