removed user email from post details page  #47
VaibhavArora314/StyleShare pull request #77
Opened 2024-06-02 08:21 UTC by Parth18Shah

# Pull Request for Issue  #47

### Title
Removed the user email from the post details page and added a back button on it for better navigation

### Description
For security reasons, the email displayed at the bottom of the post details page is removed.

### Related Issues
N/A

### Changes Made
Mentioned above

### Checklist 

- [x ] I have tested the changes locally
- [ ] Documentation has been updated (if necessary)
- [x ] Changes are backward-compatible

### Screenshots (if applicable)
N/A

### Additional Notes
N/A

Footer

2024-06-02 15:50 UTC, VaibhavArora314 requested changes
remove the user email from api also as it can be extracted by inspecting
also, did you by chance also push changes for the preview feature in this pr?

2024-06-02 17:59 UTC, Parth18Shah commented
Oh yes, will remove the user email from the API as well. Regarding the commits preview feature, yes, I did it to prevent any conflicts because both of my PRs dealt with the same files.

2024-06-02 19:54 UTC, Ultimateutkarsh11 approved these changes

2024-06-03 03:14 UTC, VaibhavArora314 approved these changes

2024-06-03 03:14 UTC, merged